# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0eba3fa85f1e6a29d65f52f3b48736bb4ae6d7da193d955763090b7cc2aa2d7ccbe6d192f7cfe09dd23ff1d9fe4862b8b5f8a3b3e74be25e36b2e0dcf84cac

test:
  secret_key_base: 19b2323941f6d7223bbac9fc422052fac348336203f01806393e2fb3d28c2f56243c351e6bbf61dde5508d0f7343d96b20ef38cd7dff64c2a4644be5c08cab54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
